[project]
name = "django-tree-menu"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
